substitutions:
    _IMAGE_NAME: 'ci-cd'
    _CLOUDRUN_SERVICE_NAME: 'ci-cd'
    _REGION: 'europe-north1'

steps:
  - name: python:3.8
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python:3.8
    entrypoint: python
    args: ['-m', 'unittest', 'discover', '-s', 'tests']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build', '-t',
        'eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', '.'
    ]
